dcat:
  rules:
    skos_rules: /../node_modules/@milieuinfo/maven-metadata-generator-npm/src/n3/skos-rules.n3
    dcterms_rules: /../node_modules/@milieuinfo/maven-metadata-generator-npm/src/n3/dcterms-rules.n3
    dcat_rules : /../node_modules/@milieuinfo/maven-metadata-generator-npm/src/n3/dcat3-rules.n3
    foaf_rules : /../node_modules/@milieuinfo/maven-metadata-generator-npm/src/n3/foaf-rules.n3
    void_rules : /../node_modules/@milieuinfo/maven-metadata-generator-npm/src/n3/void-rules.n3
    rdf_rules: /../node_modules/@milieuinfo/maven-metadata-generator-npm/src/n3/rdf-rules.n3
    spdx_rules: /../node_modules/@milieuinfo/maven-metadata-generator-npm/src/n3/spdx-rules.n3
    spdx_extra_rules: /../node_modules/@milieuinfo/maven-metadata-generator-npm/src/n3/spdx-extra-rules.n3
    ssd_rules: /../node_modules/@milieuinfo/maven-metadata-generator-npm/src/n3/ssd-rules.n3

ap :
  path: /../node_modules/@milieuinfo/maven-metadata-generator-npm/src/dcat-ap-constraints/dcat-ap-constraints.ttl

pom :
  path : '../pom.xml'

