

source:
  path: ./source/
  codelijst_csv: codelijst-source.csv
  codelijst_context: codelijst_context.json
  codelijst_csv_result_context: codelijst_csv_result_context.json
  context: context.json

dcat:
  path_catalog: /tmp/dcat/be/vlaanderen/omgeving/data/id/catalog/
  path_dataset: /tmp/dcat/be/vlaanderen/omgeving/data/id/dataset/
  name: codelijst-matrix
  dataset_jsonld: dataset.jsonld
  dataset_turtle: dataset.ttl
  catalog_turtle: catalog.ttl
  catalog_jsonld: catalog.jsonld

ap :
  path: ./main/resources/be/vlaanderen/omgeving/data/id/ontology/
  type: ap-constraints
  name: matrix
  turtle: .ttl

n3 :
  skos_rules : ./n3/skos-rules.n3
  dcat_rules : ./n3/dcat-rules.n3
  dcterms_rules : ./n3/dcterms-rules.n3
  foaf_rules : ./n3/foaf-rules.n3
  void_rules : ./n3/void-rules.n3
  rdf_rules : ./n3/rdf-rules.n3
  spdx_rules : ./n3/spdx-rules.n3
  spdx_extra_rules : ./n3/spdx-extra-rules.n3

metadata :
  catalog :
    uri : https://data.omgeving.vlaanderen.be/id/catalog
    type: http://www.w3.org/ns/dcat#Catalog
  all :
    accessURL : https://github.com/milieuinfo/codelijst-matrix.git
    contactPoint : https://data.omgeving.vlaanderen.be/id/vcard/helpdesk
    license : http://data.vlaanderen.be/id/licentie/modellicentie-gratis-hergebruik/v1.0
    publisher : http://data.vlaanderen.be/id/organisatie/OVO003323
    rightsHolder :  http://data.vlaanderen.be/id/organisatie/OVO003751
    theme :
      - http://eurovoc.europa.eu/2407
      - http://publications.europa.eu/resource/authority/data-theme/ENVI
      - http://vocab.belgif.be/auth/datatheme/ENVI
      - http://www.eionet.europa.eu/gemet/concept/10087
    spatial :
      - http://publications.europa.eu/resource/authority/country/BEL
      - https://sws.geonames.org/3337388/
    access_rights :  http://publications.europa.eu/resource/authority/access-right/PUBLIC
    accrualPeriodicity : http://publications.europa.eu/resource/authority/frequency/IRREG
    dct.language : http://publications.europa.eu/resource/authority/language/NLD
    landingPage  : https://data.omgeving.vlaanderen.be/doc/catalog/codelijst.html

  dataset :     
    temporal : https://data.omgeving.vlaanderen.be/id/periodoftime/dataset_omg
    type : http://www.w3.org/ns/dcat#Dataset
  distribution :
    csv :
      mediaType : https://www.iana.org/assignments/media-types/text/csv
      format : http://publications.europa.eu/resource/authority/file-type/CSV
      type : http://www.w3.org/ns/dcat#Distribution
    ttl:
      mediaType: https://www.iana.org/assignments/media-types/text/csv
      format: http://publications.europa.eu/resource/authority/file-type/CSV
      type : http://www.w3.org/ns/dcat#Distribution
    jsonld:
      mediaType: https://www.iana.org/assignments/media-types/text/csv
      format: http://publications.europa.eu/resource/authority/file-type/CSV
      type : http://www.w3.org/ns/dcat#Distribution
    jar :
      mediaType : https://www.iana.org/assignments/media-types/text/csv
      format : http://publications.europa.eu/resource/authority/file-type/JAR
      type :
        - http://www.w3.org/ns/dcat#Distribution
types : matrixtypes

prefixes :
  access_right: http://publications.europa.eu/resource/authority/access-right/
  adms: http://www.w3.org/ns/adms#
  assettype: http://purl.org/adms/assettype/
  conceptscheme: https://data.omgeving.vlaanderen.be/id/conceptscheme/
  country: http://publications.europa.eu/resource/authority/country/
  datasets: https://datasets.omgeving.vlaanderen.be/
  datatheme_be: http://vocab.belgif.be/auth/datatheme/
  datatheme_eu: http://publications.europa.eu/resource/authority/data-theme/
  dcat: http://www.w3.org/ns/dcat#
  dc: http://purl.org/dc/elements/1.1/
  dcterms: http://purl.org/dc/terms/
  dct: http://purl.org/dc/terms/
  eurovoc: http://eurovoc.europa.eu/
  file_type: http://publications.europa.eu/resource/authority/file-type/
  foaf: http://xmlns.com/foaf/0.1/
  formats: http://www.w3.org/ns/formats/
  frequency: http://publications.europa.eu/resource/authority/frequency/
  gemet: http://www.eionet.europa.eu/gemet/concept/
  licence: http://data.vlaanderen.be/id/licentie/modellicentie-gratis-hergebruik/
  metadata: https://data.omgeving.vlaanderen.be/ns/metadata#
  omg_catalog: https://data.omgeving.vlaanderen.be/id/catalog/
  omg_catalog_doc: https://data.omgeving.vlaanderen.be/doc/catalog/
  omg_collection: https://data.omgeving.vlaanderen.be/id/collection/
  omg_conceptscheme: https://data.omgeving.vlaanderen.be/id/conceptscheme/
  omg_dataservice: https://data.omgeving.vlaanderen.be/id/dataservice/
  omg_dataset_doc: https://data.omgeving.vlaanderen.be/doc/dataset/
  omg_dataset: https://data.omgeving.vlaanderen.be/id/dataset/
  omg_distribution_doc: https://data.omgeving.vlaanderen.be/doc/distribution/
  omg_distribution: https://data.omgeving.vlaanderen.be/id/distribution/
  omg_graphcollection: https://data.omgeving.vlaanderen.be/id/graphcollection/
  omg_graph: https://data.omgeving.vlaanderen.be/id/graph/
  omg_id: https://data.omgeving.vlaanderen.be/id/
  omg_named_graph: https://data.omgeving.vlaanderen.be/id/namedgraph/
  omg_ontology: https://data.omgeving.vlaanderen.be/id/ontology/
  omg_package: https://data.omgeving.vlaanderen.be/id/package/
  omg_periodoftime: https://data.omgeving.vlaanderen.be/id/periodoftime/
  omg_service: https://data.omgeving.vlaanderen.be/id/service/
  omg_vcard: https://data.omgeving.vlaanderen.be/id/vcard/
  ovo: http://data.vlaanderen.be/id/organisatie/
  owl: http://www.w3.org/2002/07/owl#
  repo: https://repo.omgeving.vlaanderen.be/artifactory/release/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sd: http://www.w3.org/ns/sparql-service-description#
  skos: http://www.w3.org/2004/02/skos/core#
  spdx: http://spdx.org/rdf/terms#
  ssd: http://www.w3.org/ns/sparql-service-description#
  ts: http://www.w3.org/ns/formats/
  vcard: http://www.w3.org/2006/vcard/ns#
  vlcs: https://data.omgeving.vlaanderen.be/id/conceptscheme/
  void: http://rdfs.org/ns/void#
  xsd: http://www.w3.org/2001/XMLSchema#



